#!/bin/bash
#PBS -N fastqc.raw
#PBS -S /bin/bash
#PBS -q UCTlong
#PBS -l nodes=1:series600:ppn=2
#PBS -l walltime=01:00:00
#PBS -m abe
#PBS -d /researchdata/fhgfs/cbio/cbio/courses/IBS5004Z/variant_calling/gerrit/process/
#PBS -M gerrit.botha@uct.ac.za

## Read config file
config="/home/gerrit/humgen-hpc/config.txt"
. $config

## Record start time
start_time=$(date +%s)

## Create out dir if it does not exist
if [ ! -d $fastqc_out_dir ];
 then
   mkdir -p $fastqc_out_dir
fi

## Create command string, record and run
cmd="$fastqc_base/fastqc $raw_read_dir/*.fq -f fastq -o $fastqc_out_dir -t $fastqc_cores"
echo $cmd
eval $cmd

## Record run time
end_time=$(date +%s)
diff_time=$(( $end_time - $start_time ))
echo "$diff_time seconds"
echo "`echo "scale=2;$diff_time/60" | bc` minutes"
