#!/bin/bash
#PBS -N gatk_select_snps.hc.mark_duplicates.bwa_mem.raw
#PBS -S /bin/bash
#PBS -q UCTlong
#PBS -l nodes=1:series600:ppn=1
#PBS -l walltime=01:00:00
#PBS -m abe
#PBS -d /researchdata/fhgfs/cbio/cbio/courses/IBS5004Z/variant_calling/gerrit/process/
#PBS -M gerrit.botha@uct.ac.za

## Read config file
config="/home/gerrit/humgen-hpc/config.txt"
. $config

start_time=$(date +%s)

## Create tmp dir if it does not exist
if [ ! -d $tmp_dir ];
 then
   mkdir -p $tmp_dir
fi

cmd="$java_base/java -Djava.io.tmpdir=$tmp_dir -jar $gatk_base/GenomeAnalysisTK.jar \
-l INFO \
-R $ref \
-T SelectVariants \
-V $gatk_raw_calls \
-o $gatk_raw_snps \
-selectType SNP  \
-L 1 \
-nt 1 \
-nct 1"

echo $cmd
eval $cmd

end_time=$(date +%s)
diff_time=$(( $end_time - $start_time ))
echo "$diff_time seconds"
echo "`echo "scale=2;$diff_time/60" | bc` minutes"
