#!/bin/bash
#PBS -N mark_duplicates.bwa_mem.raw
#PBS -S /bin/bash
#PBS -q UCTlong
#PBS -l nodes=1:series600:ppn=10
#PBS -l walltime=01:00:00
#PBS -m abe
#PBS -d /researchdata/fhgfs/cbio/cbio/courses/IBS5004Z/variant_calling/gerrit/process/
#PBS -M gerrit.botha@uct.ac.za

## Read config file
config="/home/gerrit/humgen-hpc/config.txt"
. $config

start_time=$(date +%s)

## Create tmp dir if it does not exist
if [ ! -d $tmp_dir ];
 then
   mkdir -p $tmp_dir
fi

cmd="$java_base/java -Djava.io.tmpdir=$tmp_dir -jar $picard_base/MarkDuplicates.jar I=$sorted_bam.bam O=$marked_duplicates_bam METRICS_FILE=$marked_duplicates_bam.metrics CREATE_INDEX=true"
echo $cmd
eval $cmd

end_time=$(date +%s)
diff_time=$(( $end_time - $start_time ))
echo "$diff_time seconds"
echo "`echo "scale=2;$diff_time/60" | bc` minutes"
